### PR TITLE
Seq property fixes

### PR DESCRIPTION
**Pull request by mowczare**
Resolves https://github.com/UdashFramework/udash-core/pull/246

### CODE REVIEW

**Comment by mowczare** [comment]
You are absolutely right, this PR purpose is only to allow user creating models with all the subclasses of `scala.collection.Seq`.

According to the https://github.com/UdashFramework/udash-core/pull/246 API restriction was not the way to go. It was a decision between model selection elasticity (and accepting possible structure copies) and model restrictions (as in aforementioned PR).

I prefer the elastic approach. Why should we return compilation errors if someone has `scala.collection.mutable.Buffer[T]` in model and want to get `.subSeq`? Same with the immutable equivalent.
That said, I'm open for a discussion.

**Comment by Starzu** [comment]
Could you prepare a benchmark comparing operations on model with `Seq` and `ISeq`?

You've created a lot of compilation related tests, but could you also add some runtime tests?

**Comment by mowczare** [comment]
I've added a benchmark for creating `ModelProperty` with the different type of Seq. As @ghik noticed, obtaining the seq-like value to different models than `Seq` has visible time overhead.

**Comment by ghik** [comment]
Not having too much to do with frontend or Udash development, I don't feel like I can give any meaningful feedback on this.

**Comment by Starzu** [comment]
I think it's ok, but you should add a note in `subSeq` docs and guide.

**Comment by mowczare** [comment]
Added both doc in `subSeq` and paragraph in guide:
https://github.com/UdashFramework/udash-guide/pull/43

@Starzu, please review.

**Pull request merged**
